# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170329_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactphone',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contact'),
        ),
    ]
